name: '2nd Demo'
on: 
  workflow_dispatch:
    inputs:
      oupath: 
        description: 'Target OU'
        default: 'OU=Test'
        required: true
      
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Read Vars
        run: echo "Hello ${{ github.event.inputs.oupath }}"
